[theme.clay-dark]
name = "clay dark"
isDark = true
vim = "fluoromachine"
kitty = "kaolin-galaxy"
plasma = "ClayDark"
accent = "#A85CB8"
tmux = "catppuccin/mocha"

[theme.clay-light]
name = "clay light"
vim = "catppuccin-latte"
kitty = "flexoki-light"
plasma = "ClayLight"
accent = "#A85CB8"
tmux = "catppuccin/latte"
